### ISSUE TITLE
kli agent command says it starts TCP service but none is started

### ISSUE THREAD

**Issue by paulfdietrich** [WebOfTrust/keripy#161]
I started an agent with 
```
$ kli agent start -I 

******* Starting agent listening: http/5623, tcp/5621 .******
```

and presumed that there was some TCP interface started.

But confirmed with wireshark and this command that it does not start any TCP listener on this port but just the admin interface. 

```
$ sudo lsof -i -P | grep -i python
Password:
Python    95584  xxxxxxx    7u  IPv4 0xbb3c6d80318c9993      0t0    TCP *:5623 (LISTEN)
```

**Comment by pfeairheller** [comment]
Yes, that was removed when we refactored the agent to support boot APIs and encrypted keystone. 

The intention is to add it back when we can figure out what it means in an agent that needs to be unlocked. 

But perhaps it's best now to remove that command line flag and update the message and create another issue to track the work of reenabling TCP support for direct mode connections.

**Comment by paulfdietrich** [comment]
is it current possible to set up a direct mode delegator/delegate connection without using witnesses via KLI?  

The examples in scripts seem to use witnesses and gobi.

**Comment by pfeairheller** [comment]
No it is not currently possible.  The problem is that the recent addition of full support for multiple local identifiers for a single key store forced us to change the semantics of the agent.  It now serves as an agent for multiple identifiers.  As a consumer of mailbox messages it was easy to create pollers for each new identifier that is created.  But for direct connections over either TCP or HTTP, the connection needs to be dedicated to a single identifier so the agent knows what keys to use to sign receipts, messages, etc.

For example, the witness code allows only one identifier and launches external listeners on only one TCP and HTTP port for that identifier.  We would need to create the equivalent type of agent for a controller or figure out an approach that would let the current agent launch listeners on specific ports, perhaps at the bequest of a new API call.  

In any event, our current use cases only require agents that accept incoming messages from mailboxes so it is not a problem we have attempted to address yet.

**Comment by SmithSamuelM** [comment]
We have not discussed this to any significant degree internally, But basically we will need some form of introduction (aka OOBI) for each side of a direct mode TCP connection (duplex channel). This could be implicit like the first packet sent is the inception event of the AID of the sender’s side and the first packet sent in response on that connection is the inception event  AID of the replier.  Absent such an implicit introduction we would have to define an introduction message to formally indicate the AIDs of each side.

For the last few months, we have been mostly focused on the much harder problems of indirect mode.

**Comment by pfeairheller** [comment]
Agent has been removed from KERIpy, replaced by WEbOfTrust/KERIA
