### ISSUE TITLE
Chore - update qnfs database to using subing.Suber

### ISSUE THREAD

**Issue by m00sey** [WebOfTrust/keripy#834]
Currently the `.qnfs` sub db uses the "legacy" 😬 approach of creating a `Baser` property and adding methods to `Baser`

The sub db created here:
https://github.com/WebOfTrust/keripy/blob/ce3c235faf9aa99580ee49dcd3c6b36f27c5fdd7/src/keri/db/basing.py#L997

The additional functionality added to `Baser` here:
https://github.com/WebOfTrust/keripy/blob/ce3c235faf9aa99580ee49dcd3c6b36f27c5fdd7/src/keri/db/basing.py#L3031

Newer sub dbs that have been added using the `subing.Suber` and associated classes:
https://github.com/WebOfTrust/keripy/blob/ce3c235faf9aa99580ee49dcd3c6b36f27c5fdd7/src/keri/db/subing.py#L197

The chore is to update usages of the `.qnfs` associated functionality from `Baser` and implement it as a `subing.Suber`:

`self.qnfs = subing.Suber(db=self, subkey="qnfs.")`

`**.db.addQnf` becomes `**db.qnfs.add`

- [ ] add new subing.Suber qnfs sub db to basing
- [ ] remove old .qnfs initialization 
- [ ] updated usages of putQnfs
- [ ] removed putQnfs
- [ ] updated usages of addQnf
- [ ] removed addQnf
- [ ] updated usages of getQnfs
- [ ] removed getQnfs
- [ ] updated usages of getQnfLast
- [ ] removed getQnfLast
- [ ] updated usages of getQnfItemsNext
- [ ] removed getQnfItemsNext
- [ ] updated usages of getQnfItemsNextIter
- [ ] removed getQnfItemsNextIter
- [ ] updated usages of cntQnfs
- [ ] removed cntQnfs
- [ ] updated usages of delQnfs
- [ ] removed delQnfs
- [ ] updated usages of delQnf
- [ ] removed delQnf

**Comment by arilieb** [comment]
Working on this now

**Comment by arilieb** [comment]
Question: delQnf is used to delete a single escrow value at a given key. I am attempting to replace this with functionality from subing.Suber in eventing.py. the Suber class does not have built in functionality for this, as its rem method removes the everything stored at the key, rather than a single value. Which, if any, of the following approaches should I take?

- use a different class, perhaps IoSetSuber, as the rem function from that class seems suited to the task
- use get and pin methods from the Suber class to overwrite the set of values at key with the the values minus the deleted value
- write a new method in the Suber class

**Comment by pfeairheller** [comment]
You have to look at the existing definition of the`qnf` database.  If is an "insertion order set", (usually indicated by `dupsort=True` in the table creation), you HAVE to use `IoSetSuber`.  That is the only way this will be a proper replacement.

**Comment by arilieb** [comment]
Created PR with the discussed changes. https://github.com/WebOfTrust/keripy/pull/849

**Comment by m00sey** [comment]
Closed by #849
